kind: pipeline
type: docker
name: mysql_backup

steps:
  - name: config
    image: plugins/docker
    environment:
      CONFIG_FILE:
        from_secret: config_file
    commands:
      - echo -e "$CONFIG_FILE" > ./config.yml

  - name: deploy
    image: drillster/drone-rsync
    depends_on:
      - config
    when:
      branch:
        - master
    settings:
      hosts:
        - 139.162.20.83
      key:
        from_secret: key
      port: 22
      command_timeout: 2m
      target: ~/mysql/backup
      script:
        - cd ~/mysql/backup
        - python3 -m venv venv
        - source venv/bin/activate
        - pip install -r requirements.txt
        - python3 backup.py

trigger:
  branch:
    - master
